version: "3.9"

services:
  db:
    build:
      context: libs/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ppa
