---
A utility workflow to synchronize the `.github/labels.yml` manifest with the repository's currently available labels.

[Read More](https://github.com/micnncim/action-label-syncer)
---
name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
