#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --name-only --diff-filter=ACM | grep ts &>/dev/null; then
  echo "Checking for TypeScript errors..."
  npx tsc -p . --noEmit
  npx tsc -p apps/documentation --noEmit
  npx tsc -p apps/documentation/cdk --noEmit
  echo "...none found."
fi

npx lint-staged
