# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Clean up staging environments for pull request

on:
  pull_request:
    types:
      - closed
      - labeled

concurrency:
  group: cleanup-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write
  repository-projects: write

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  NODE_ENV: staging
  PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  setup:
    name: Setup the repository

    if: (github.event.action == 'labeled' && github.event.label.name == 'no deploy') || github.event.action == 'closed'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and setup pnpm
        uses: ./.github/actions/checkout-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  cleanup-api:
    name: Clean up API staging environment for pull request

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Build AntStack
        run: pnpm build --filter="ant-stack"

      - name: Link AntStack
        run: pnpm link ant-stack

      - name: Wait for API CloudFormation stack to idle
        uses: ./.github/actions/wait-for-cloudformation-stack-idle
        with:
          stack_name: peterportal-api-next-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Destroy API stack
        run: pnpm destroy --filter="ant-stack"

      - name: Set API staging environment as inactive
        uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging-${{ github.event.pull_request.number }}
          onlyDeactivateDeployments: true

  cleanup-documentation:
    name: Clean up documentation staging environment for pull request

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Build documentation CDK
        run: pnpm build --filter="docs-cdk"

      - name: Wait for documentation CloudFormation stack to idle
        uses: ./.github/actions/wait-for-cloudformation-stack-idle
        with:
          stack_name: peterportal-api-next-docs-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Destroy documentation stack
        run: pnpm destroy --filter="docs-cdk"

      - name: Set environment as inactive
        uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging-${{ github.event.pull_request.number }}-docs
          onlyDeactivateDeployments: true
