---
name: Clean up staging PR (API)
on:
  pull_request:
    types:
      - closed
      - labeled
concurrency:
  group: api-${{ github.head_ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write
  repository-projects: write
jobs:
  clean-up:
    if: (github.event.action == 'labeled' && github.event.label.name == 'no deploy')
      || github.event.action == 'closed'
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      NODE_ENV: staging
      PR_NUM: ${{ github.event.pull_request.number }}
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build AntStack
        run: pnpm build --filter="ant-stack"

      - name: Link AntStack
        run: pnpm link ant-stack

      - name: Build assets
        run: pnpm build --filter="api-*"

      - name: Wait for API stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Destroy deployed stacks
        run: pnpm destroy --filter="ant-stack"

      - name: Set environment as inactive
        if: github.event.action == 'labeled' && github.event.label.name == 'no deploy'
        uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging-${{ github.event.pull_request.number }}
          onlyDeactivateDeployments: true

      - name: Delete environment
        if: github.event.action == 'closed'
        uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging-${{ github.event.pull_request.number }}
