name: Lint PR title and message

permissions:
  pull-requests: write

on:
  pull_request_target:

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint PR title
        run: echo ${{ toJSON(github.event.pull_request.title) }} | npx commitlint

      - name: Format PR title
        id: devmoji
        run: |
          echo TITLE=$(npx devmoji --format shortcode --text ${{ toJSON(github.event.pull_request.title) }}) >> "$GITHUB_OUTPUT"

      - name: Update Pr title
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.number }}
          title: ${{ toJSON(steps.devmoji.outputs.TITLE) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
