# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Lint and Format PR Title and Message

permissions:
  pull-requests: write

on:
  pull_request:

jobs:
  lint-and-format-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install devDependencies
        run: pnpm install --dev --frozen-lockfile --ignore-scripts --workspace-root

      - name: Lint PR title
        run: echo ${{ github.event.pull_request.title }} | npx --no -- commitlint

      - name: Format PR title
        id: devmoji
        run: |
          TITLE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(github.event.pull_request.title) }})
          echo TITLE=$TITLE >> "$GITHUB_OUTPUT"

      - name: Update PR title
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.number }}
          title: ${{ toJSON(steps.devmoji.outputs.TITLE) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
