---
name: Deploy docs to production
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: production-docs
      url: https://docs.api-next.peterportal.org
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      NODE_ENV: production

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: NODE_ENV=development pnpm install --frozen-lockfile

      - name: Build docs assets
        run: pnpm build --filter="docs-cdk"

      - name: Wait for docs stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-docs-prod
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Deploy stack
        run: pnpm run deploy --filter="docs-cdk"
