# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Deploy CloudFormation stacks and staging environments for pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - unlabeled

permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  NODE_ENV: staging
  PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  deploy-api:
    name: Deploy API CloudFormation stack and staging environment for pull request

    if: (!contains(github.event.pull_request.labels.*.name, 'no deploy'))

    runs-on: ubuntu-latest

    environment:
      name: staging-${{ github.event.pull_request.number }}
      url: https://staging-${{ github.event.pull_request.number }}.anteaterapi.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm build --filter="@apps/api"

      - name: Deploy API CloudFormation stack
        run: pnpm --filter="@apps/api" cdk-app deploy
