# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Lint and format PR title and message

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  lint-and-format-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Setup NodeJS and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: Install devDependencies
        run: pnpm install --dev --frozen-lockfile --ignore-scripts --workspace-root

      - name: Lint PR title
        run: echo ${{ toJSON(github.event.pull_request.title) }} | npx --no -- commitlint

      - name: Format PR title
        id: devmoji
        run: |
          TITLE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(github.event.pull_request.title) }})
          echo TITLE=$TITLE >> "$GITHUB_OUTPUT"

      - name: Update PR title if needed
        if: toJSON(github.event.pull_request.title) != toJSON(steps.devmoji.outputs.TITLE)
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.number }}
          title: ${{ toJSON(steps.devmoji.outputs.TITLE) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
