---
name: Deploy PR to staging
on:
  pull_request:
    types:
      - opened
      - synchronize
      - unlabeled
permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  deploy:
    if: (!contains(github.event.pull_request.labels.*.name, 'no deploy'))
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      NODE_ENV: staging
      PR_NUM: ${{ github.event.pull_request.number }}

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Wait for API stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Wait for docs stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-docs-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Deploy stacks
        run: pnpm deploy -- --filter="api-cdk" --filter="docs-cdk"

      - name: Comment staging URLs
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: stagingURL
          recreate: true
          message: 🚀 Staging instances deployed!\nAPI - https://staging-${{
            github.event.pull_request.number }}.api-next.peterportal.org\nDocs - to
            https://staging-${{ github.event.pull_request.number }}-docs.api-next.peterportal.org
