# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Deploy API staging environment for pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - unlabeled

permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write

concurrency:
  group: staging-${{ github.head_ref }}
  cancel-in-progress: true

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  NODE_ENV: staging
  PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  setup:
    name: Setup the repository

    if: (!contains(github.event.pull_request.labels.*.name, 'no deploy'))

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and setup pnpm
        uses: ./.github/actions/checkout-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  deploy-staging-api:
    name: Deploy API staging environment

    runs-on: ubuntu-latest

    needs: setup

    environment:
      name: staging-${{ github.event.pull_request.number }}
      url: https://staging-${{ github.event.pull_request.number }}.api-next.peterportal.org

    steps:
      - name: Build AntStack
        run: pnpm build --filter="ant-stack"

      - name: Link AntStack
        run: pnpm link ant-stack

      - name: Build API assets
        run: pnpm build --filter="api-*"

      - name: Wait for API stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Deploy stack
        run: pnpm run deploy --filter="ant-stack"

  deploy-staging-documentation:
    name: Deploy documentation staging environment

    runs-on: ubuntu-latest

    needs: setup

    environment:
      name: staging-${{ github.event.pull_request.number }}-docs
      url: https://staging-${{ github.event.pull_request.number }}-docs.api-next.peterportal.org

    steps:
      - name: Build docs assets
        run: pnpm build --filter="docs-cdk"

      - name: Wait for docs stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-docs-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Deploy stack
        run: pnpm run deploy --filter="docs-cdk"
