---
name: Deploy PR to staging
on:
  pull_request:
    types:
      - opened
      - synchronize
      - unlabeled
permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  deploy:
    if: (!contains(github.event.pull_request.labels.*.name, 'no deploy'))
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      NODE_ENV: staging
      PR_NUM: ${{ github.event.pull_request.number }}

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript type checking
        run: npx tsc -p . --noEmit && npx tsc -p apps/docs --noEmit && npx tsc -p apps/docs/cdk --noEmit

      - name: Build AntStack
        run: pnpm build --filter="ant-stack"

      - name: Install dependencies (again)
        run: pnpm install --frozen-lockfile

      - name: Build assets
        run: pnpm build

      - name: Wait for API stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Wait for docs stack to stabilize
        uses: ./.github/actions/stabilize-stack
        with:
          stack_name: peterportal-api-next-docs-staging-${{ github.event.pull_request.number }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}

      - name: Deploy stacks
        run: pnpm run deploy --filter="ant-stack" --filter="docs-cdk"

      - name: Comment staging URLs
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: stagingURL
          recreate: true
          message: 🚀 Staging instances deployed!

            API - https://staging-${{ github.event.pull_request.number }}.api-next.peterportal.org

            Docs - https://staging-${{ github.event.pull_request.number }}-docs.api-next.peterportal.org
