---
name: Deploy PR to staging
on:
  pull_request:
    types:
      - opened
      - synchronize
      - unlabeled
permissions:
  id-token: write
  contents: read
  deployments: write
  pull-requests: write
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  deploy:
    if: (!contains(github.event.pull_request.labels.*.name, 'no deploy'))
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
      NODE_ENV: staging
      PR_NUM: ${{ github.event.pull_request.number }}
      TURBO_API: ${{ secrets.TURBO_API }}
      TURBO_TEAM: team_peterportal_api_next
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy pull request
        run: npm run deploy
      - name: Comment staging URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: stagingURL
          recreate: true
          message: Deployed staging instance to https://staging-${{
            github.event.pull_request.number }}.api-next.peterportal.org
