---
Ensure that pull request titles are up to Los Pollos standards.
---
name: Lint PR title and message

on:
  pull_request_target:

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: Namchee/conventional-pr@v0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          close: false
          body: false
          issue: false
